Vagrant.configure("2") do |config|
	config.vm.provider "virtualbox" do |vb|
		vb.linked_clone = true
	end

	config.vm.define "DNS" do |dns|
		dns.vm.box = "rysDebian"
		dns.vm.hostname = "Servidor"
		dns.vm.provider "virtualbox" do |v|
			v.name = "DNS"
			v.gui = true
		end
	end
end