Vagrant.configure("2") do |config|
	config.vm.provider "virtualbox" do |vb|
		vb.linked_clone = true
	end

	config.vm.define "Host1" do |host1|
		host1.vm.box = "rysDebian"
		host1.vm.hostname = "Host1"
		host1.vm.network "private_network", ip: "192.168.1.1", virtualbox__intnet: "red1"
		host1.vm.provider "virtualbox" do |v|
			v.name = "Host 1"
			v.gui = true
		end
		host1.vm.provision "shell", inline: <<-SHELL
			# sudo ifconfig enp0s3 down || No se puede desactivar el adaptador NAT porque si no la conexión SSH deja de funcionar y Vagrant se cuelga
			sudo service network-manager stop
			sudo route add default gw 192.168.1.10 dev enp0s8
		SHELL
	end
	config.vm.define "Host2" do |host2|
		host2.vm.box = "rysDebian"
		host2.vm.hostname = "Host2"
		host2.vm.network "private_network", ip: "192.168.1.2", virtualbox__intnet: "red1"
		host2.vm.provider "virtualbox" do |v|
			v.name = "Host 2"
			v.gui = true
		end
		host2.vm.provision "shell", inline: <<-SHELL
			# sudo ifconfig enp0s3 down || No se puede desactivar el adaptador NAT porque si no la conexión SSH deja de funcionar y Vagrant se cuelga
			sudo service network-manager stop			
			sudo route add default gw 192.168.1.10 dev enp0s8
		SHELL
	end
	config.vm.define "kali" do |kali|
		kali.vm.box = "rysKali"
		kali.vm.hostname = "kali"
		kali.vm.network "private_network", ip: "192.168.1.3", virtualbox__intnet: "red1"
		kali.vm.provider "virtualbox" do |v|
			v.name = "Kali"
			v.gui = true
		end
		kali.vm.provision "shell", inline: <<-SHELL
			# sudo ifconfig eth0 down || No se puede desactivar el adaptador NAT porque si no la conexión SSH deja de funcionar y Vagrant se cuelga
			# sudo service network-manager stop			
			sudo route add default gw 192.168.1.10 dev eth1
		SHELL
	end
	config.vm.define "Router1" do |router1|
		router1.vm.box = "rysDebian"
		router1.vm.hostname = "Router1"
		router1.vm.network "private_network", ip: "192.168.1.10", virtualbox__intnet: "red1"
		router1.vm.network "private_network", ip: "192.168.2.10", virtualbox__intnet: "red2"
		router1.vm.provider "virtualbox" do |v|
			v.name = "Router 1"
			v.gui = true
		end
		router1.vm.provision "shell", inline: <<-SHELL
			sudo service network-manager stop
			# sudo ifconfig enp0s3 down || No se puede desactivar el adaptador NAT porque si no la conexión SSH deja de funcionar y Vagrant se cuelga
			sudo sysctl -w net.ipv4.ip_forward=1
		SHELL
	end
	config.vm.define "ServidorHTTP" do |servidorhttp|
		servidorhttp.vm.box = "rysMetasploit"
		servidorhttp.vm.hostname = "ServidorHTTP"
		servidorhttp.vm.network "private_network", ip: "192.168.2.20", virtualbox__intnet: "red2"
		servidorhttp.vm.provider "virtualbox" do |v|
			v.name = "Servidor HTTP"
			v.gui = true
		end
		servidorhttp.vm.provision "shell", inline: <<-SHELL
			# sudo ifconfig enp0s3 down || No se puede desactivar el adaptador NAT porque si no la conexión SSH deja de funcionar y Vagrant se cuelga
			sudo service network-manager stop
			sudo route add default gw 192.168.2.10 dev enp0s8
		SHELL
	end
end