Vagrant.configure("2") do |config|
	config.vm.provider "virtualbox" do |vb|
		vb.linked_clone = true
	end

	config.vm.define "Servidor" do |servidor|
		servidor.vm.box = "rysDebian"
		servidor.vm.hostname = "Servidor"
		servidor.vm.network "private_network", ip: "192.168.1.4", virtualbox__intnet: "red1"
		servidor.vm.provider "virtualbox" do |v|
			v.name = "Servidor"
			v.gui = true
		end
		host1.vm.provision "shell", inline: <<-SHELL
			sudo service network-manager stop
		SHELL
	end
	config.vm.define "Kali" do |kali|
		kali.vm.box = "rysKali"
		kali.vm.hostname = "Kali"
		kali.vm.network "private_network", ip: "192.168.1.3", virtualbox__intnet: "red1"
		kali.vm.provider "virtualbox" do |v|
			v.name = "Kali"
			v.gui = true
		end
	end
end